---
- name: snap | Manual Install
  snap:
    name: "{{ item.name }}"
    channel: "{{ item.channel | default(latest/stable) }}"
    classic: "{{ item.classic | default(false) }}"
    state: "{{ item.state | default(present) }}"
  with_items: "{{ snap_manual_items }}"
