---
# Docker setup
# cf. https://docs.docker.com/engine/install/ubuntu/
- name: Install docker requirement packages
  apt:
    update_cache: true
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Set up the docker stable repository.
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install docker engine
  apt:
    update_cache: true
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Ensure docker service is enabled
  systemd:
    name: docker
    state: started
    enabled: true
