---
- hosts:
    - admin
  become: true
  gather_facts: true

  roles:
    - user
    - sshd
    - apt

- hosts:
    - cluster
  become: true
  gather_facts: true

  roles:
    - user
    - sshd
    - apt
    - docker
  tasks:
    - name: Disable UFW
      ufw:
        state: disabled
