---
- name: add groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  with_items: "{{ sugardon_groups }}"
  become: true

- name: Add users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    groups: ["{{ item.groups }}"]
    state: present
  with_items: "{{ sugardon_users }}"
  become: true

- name: Add SSH authorized keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('url', item.authorized_key_url) }}"
  with_items: "{{ sugardon_users }}"
  become: true

- name: Lets wheel sudo without password (CentOS)
  lineinfile:
    line: "%wheel ALL= NOPASSWD: ALL"
    dest: /etc/sudoers

- name: Lets sudo sudo without password (Ubuntu)
  lineinfile:
    line: "%sudo ALL= NOPASSWD: ALL"
    dest: /etc/sudoers
