---
- hosts: chromebook
  connection: local
  become: true
  gather_facts: true

  roles:
    - user
    - sshd
    - apt
    - snap
    - ansible-galaxy-pyenv
    - ansible-nvm-node
    - starship
    - rcm_dotfiles
