---
- hosts: all
  become: true
  become_user: "{{ dev_tool_become_user }}"
  gather_facts: true

  roles:
    - user
    - sshd
    - apt
    - ansible-galaxy-pyenv
    - starship
    - rcm_dotfiles
