---
- hosts: all
  become: true
  gather_facts: true

  roles:
    - user
    - sshd
    - apt
    - snap
    - ansible-galaxy-pyenv
    # Use https://github.com/lukechilds/zsh-nvm instead of ansible
    # - ansible-nvm-node
    - starship
    - rcm_dotfiles
