---
- name: rcm dotfiles | git checkout
  ansible.builtin.git:
    repo: "{{ rcm_dotfiles_git_repo }}"
    dest: "{{ rcm_dotfiles_git_dest }}"
    version: "{{ rcm_dotfiles_git_version }}"

- name: rcm dotfiles | rcup
  shell: RCRC={{ rcm_dotfiles_git_dest }}/rcrc rcup
  args:
    chdir: "{{ rcm_dotfiles_git_dest }}"
  become: true
  become_user: "{{ rcm_dotfiles_user }}"

- name: rcm dotfiles | owner
  file:
    path: "{{ rcm_dotfiles_git_dest }}"
    owner: "{{ rcm_dotfiles_user }}"
    recurse: true
