---
- name: rcm dotfiles | git checkout
  ansible.builtin.git:
    repo: "{{ rcm_dotfiles_git_repo }}"
    dest: "{{ rcm_dotfiles_git_dest }}"
    version: "{{ rcm_dotfiles_git_version }}"

- name: rcm dotfiles | rcup
  shell: rcup
  args:
    chdir: "{{ rcm_dotfiles_git_dest }}"
  become: no
  remote_user: "{{ rcm_dotfiles_user }}"
