---
- hosts: jetsonnano
  become: true
  gather_facts: true

  roles:
    - user
    - sshd
    - apt
    - jetson_nano_common
    - ansible-galaxy-pyenv

- hosts: raspberrypi
  become: true
  gather_facts: true

  roles:
    - user
    - sshd
    - apt
    - ansible-galaxy-pyenv
