---
- hosts: jetsonnano
  become: true
  gather_facts: true

  roles:
    - user
    - sshd
    - apt
    - jetson_nano_common
    - ansible-galaxy-pyenv
  tasks:
    # Should disable ipv6
    # cf. https://serverfault.com/questions/957161/error-when-trying-to-enable-ufw-logs-on-ubuntu
    - name: Disable UFW
      ufw:
        state: disabled

- hosts: raspberrypi
  become: true
  gather_facts: true

  roles:
    - user
    - sshd
    - apt
    - raspberrypi_common
    - ansible-galaxy-pyenv
  tasks:
    - name: Disable UFW
      ufw:
        state: disabled

# TODO: Should check DNS server
