---
- name: starship | Download install.sh
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: 0755

- name: starship | Install
  shell: /tmp/starship_install.sh
  become: true

- name: starship | Remove install.sh
  file:
    path: /tmp/starship_install.sh
    state: absent
