---
- name: Selinux Disabled
  selinux:
    state: disabled
  register: selinux
  become: true

- name: Update dnf packages
  dnf:
    name: '*'
    state: latest
  become: true

- name: install vim
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - vim
    state: present
  become: true

- name: reboot
  reboot:
    reboot_timeout: 3600
  when: selinux.reboot_required
  become: true
